from typing import Any

class SimpleDocTemplate:
    page: int

    def __init__(self, *args: object, **kwargs: Any) -> None: ...
    def handle_pageBegin(self) -> None: ...
    def build(self, flowables: list[object], **kwargs: Any) -> None: ...

class Paragraph:
    def __init__(self, text: str, style: object) -> None: ...

class Spacer:
    def __init__(self, width: float, height: float) -> None: ...
