from typing import Any

class Canvas:
    def __init__(self, filename: object, **kwargs: Any) -> None: ...
    def setTitle(self, value: str) -> None: ...
    def setAuthor(self, value: str) -> None: ...
    def setCreator(self, value: str) -> None: ...
    def setSubject(self, value: str) -> None: ...
    def setFont(self, name: str, size: float) -> None: ...
    def drawRightString(self, x: float, y: float, text: str) -> None: ...
