"""企业资料持久化端口；调用者事务内重新读取当前员工权限。"""
from __future__ import annotations

from datetime import datetime
from types import TracebackType
from typing import Protocol, Self

from domains.products.knowledge_schemas import (
    KnowledgeDocumentView,
    KnowledgeJob,
    KnowledgeRevisionView,
)
from shared.schemas.identifiers import EmployeeId, TenantId


class KnowledgeRepository(Protocol):
    async def lock(self) -> None: ...
    async def employee_identity(self, employee_id: EmployeeId) -> tuple[str, str] | None: ...
    async def source_matches(self, document: KnowledgeDocumentView) -> bool: ...
    async def get_document(self, document_id: str) -> KnowledgeDocumentView | None: ...
    async def get_by_artifact(self, artifact_id: str) -> KnowledgeDocumentView | None: ...
    async def save_document(self, document: KnowledgeDocumentView) -> None: ...
    async def get_request(self, actor_id: EmployeeId, key_hash: str) -> tuple[str, str] | None: ...
    async def save_request(self, actor_id: EmployeeId, key_hash: str, request_hash: str, document_id: str) -> None: ...
    async def get_job(self, job_id: str) -> KnowledgeJob | None: ...
    async def save_job(self, job: KnowledgeJob) -> None: ...
    async def claimable_job(self) -> KnowledgeJob | None: ...
    async def expired_jobs(self, now: datetime) -> tuple[KnowledgeJob, ...]: ...
    async def get_revision(self, revision_id: str) -> KnowledgeRevisionView | None: ...
    async def save_revision(self, revision: KnowledgeRevisionView) -> None: ...
    async def list_documents(self, query: str, limit: int, offset: int) -> tuple[tuple[KnowledgeDocumentView, ...], int]: ...
    async def pending_exports(self, limit: int) -> tuple[KnowledgeDocumentView, ...]: ...


class KnowledgeUnitOfWork(Protocol):
    knowledge: KnowledgeRepository
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, traceback: TracebackType | None) -> None: ...


class KnowledgeUnitOfWorkFactory(Protocol):
    def __call__(self, tenant_id: TenantId) -> KnowledgeUnitOfWork: ...
