import type { components } from "../api/api";

const sourceLabels = {
  conversation: "客户会话", web_page: "网页", upload: "上传资料", employee_input: "员工录入",
  agent_inference: "智能助手推断", external_api: "外部接口",
} satisfies Record<components["schemas"]["SourceType"], string>;

const labels: Readonly<Record<string, string>> = {
  ...sourceLabels,
  required_by: "时间要求", target_price: "目标价", product_category: "产品品类", size_spec: "尺寸规格", application: "用途", packaging: "包装", dependency_unavailable: "依赖服务暂不可用",

  permission_denied: "权限不足", recovery_unavailable: "恢复暂不可用",
  public_rfq: "公开询价", tender_notice: "招标公告", inbound_inquiry: "客户询盘", trade_show_request: "展会需求",
  historical_unclosed_need: "历史未成交需求", supplier_referral: "供应商转介", product_line_expansion: "产品线扩展",
  facility_expansion: "设施扩建", new_market_entry: "进入新市场", procurement_role_hiring: "采购岗位招聘",
  distributor_change: "经销商变更", new_certification: "获得新认证", large_contract_won: "获得重大合同",
  funding_or_merger: "融资或并购", stockout_observed: "观察到缺货", negative_product_review: "产品负面评价",
  supplier_complaint: "对供应商的投诉", catalog_gap: "产品目录缺口", value_chain_adjacency: "产业链相邻需求",
  complementary_category: "互补品类", linked_to_hypothesis: "已关联需求假设", inferred: "已形成推断", contacting: "联系中",
  discovering: "发现供应中", candidates_ready: "候选已就绪", handed_to_costing: "已交接成本核算", exhausted: "寻源已穷尽",
  exact: "完全匹配", different: "存在差异", product_type: "产品类型", material: "材质", size: "尺寸", model: "型号",
  quantity_tier: "数量档", moq: "最小起订量", pricing_unit: "计价单位", currency: "币种",
  bait_price: "诱导性低价", vague_range: "价格区间不明确", ambiguous_price: "价格不明确", unit_unclear: "单位不明确",
  quantity_tier_missing: "缺少数量档", currency_unclear: "币种不明确", verification_incomplete: "核验不完整",
  moq_not_met: "未达到最小起订量", qualified_limit_reached: "合格候选数量已达上限",
  approval_required: "需要审批", quota_status_unknown: "额度状态未知", paid_usage_enabled: "付费已开启",
  quota_exhausted: "免费额度已耗尽", provider_timeout: "服务商请求超时", provider_rate_limited: "服务商请求受限",
  page_access_forbidden: "页面禁止访问", login_or_captcha: "需要登录或验证码", unsafe_redirect: "跳转地址不安全",
  no_search_results: "无搜索结果", no_results: "无搜索结果", no_verifiable_supplier: "没有可核验的供应商",
  no_qualified_candidate: "没有合格候选", opportunity_required: "缺少贸易机会", need_incomplete: "需求信息不完整",
  plan_confirmation_required: "计划尚未确认", free_quota_unavailable: "免费额度不可用", budget_exhausted: "预算已耗尽",
  manual_stop: "人工停止", intake: "任务接收", plan: "计划确认", provider: "服务商调用", page: "页面读取",
  candidate: "候选核验", review: "人工审核", cost_handoff: "成本交接", demand_first: "需求优先", supply_first: "供应优先",

  pending: "待处理", requested: "已请求", queued: "排队中", running: "运行中", executing: "执行中",
  succeeded: "已成功", failed: "失败", completed: "已完成", cancelled: "已取消", timed_out: "已超时",
  waiting_human: "等待人工", waiting_event: "等待事件", waiting: "等待中", starting: "启动中", admitted: "已准入", blocked: "已阻断",
  pending_confirmation: "待确认", authorized: "已授权", load_context: "读取上下文", generate_explanation: "生成说明", apply_result: "应用结果", catalog_product_proposal: "目录产品提案",
  draft: "草稿", pending_approval: "待审批", approved: "已批准", applied: "已生效", apply_failed: "生效失败",
  rejected: "已拒绝", expired: "已过期", superseded: "已被新版本替代", stale: "已失效", active: "已启用", paused: "已暂停",
  accepted: "已接受", reserved: "已预留", sending: "发送中", sent: "已发送", failed_transient: "暂时失败", failed_permanent: "永久失败",
  created: "已创建", auth_pending: "待认证", warming: "预热中", throttled: "已限流", suspended: "已停用", retired: "已退役",
  opened: "已建立", verifying: "核验中", planning: "规划中", searching: "搜索中", matching: "匹配中", awaiting_review: "等待审核",
  captured: "已采集", processed: "已处理", discarded: "已弃用", validated: "已验证", sourcing_ready: "可进入寻源",
  handed_to_sourcing: "已交接寻源", fulfilled: "已履行", withdrawn: "已撤回", qualified: "已合格", incomplete: "资料不完整",
  assigned: "已分配", contacted: "已联系", sourcing: "寻源中", negotiating: "洽谈中", won: "已成交", lost: "已失败",
  enrolled: "已入组", in_sequence: "序列执行中", replied: "已回复", stopped_suppressed: "因抑制名单停止",
  stopped_bounced: "因退信停止", stopped_manual: "人工停止", stopped_identity_unavailable: "发件身份不可用，已停止",
  verified: "已验证", unverified: "未验证", risky: "存在风险", invalid: "无效", confirmed: "已确认", unconfirmed: "未确认",
  current: "当前有效", missing: "缺失", blocked_by_quantity: "数量信息不足", unknown: "未知", uncertain: "结果不确定",
  confirmed_consumed: "已确认消耗", confirmed_not_consumed: "已确认未消耗", required: "需要核对",
  free: "免费", paid: "付费", low_mid: "中低", mid: "中", mid_high: "中高", very_high: "很高", extreme: "极高", low: "低", medium: "中", high: "高", critical: "严重", none: "无", zero: "零成本",
  estimated: "预估", quoted: "已报价", indicative: "参考价", actual: "实际", passed: "通过", not_required: "不要求",
  awaiting_approval_submission: "待提交审批", pending_review: "待审核", cultivation_queued: "已进入培养队列",
  no_qualified_supply: "尚无合格供应", qualified_supply_found: "已找到合格供应",
  product_launch: "新品发布", factory_expansion: "工厂扩建", hiring: "招聘动态", procurement_hiring: "采购岗位招聘",
  marketplace_seller_activity: "电商卖家动态", consumer_complaint: "消费者反馈", public_tender: "公开招标", rfq: "询价需求",
  company_news: "企业动态", social_post: "社交平台动态", exhibition: "展会线索", website_update: "网站更新",
  demand_discovery: "需求发现", account_discovery: "企业发现", outreach_campaign: "活动触达", reply_qualification: "回复识别",
  human_handoff: "人工接管", employee_work_intake: "工作资料录入", email_feedback: "邮件反馈处理", assistant: "智能助手",
  sending_identity_auth: "发件身份认证", playbook_change: "公司业务规则变更", country_policy_change: "国家政策变更",
  sourcing_case: "寻源案例", quote_approval: "报价审批", catalog_product_cultivation: "目录产品培养",
  catalog_proposal_policy_change: "目录产品政策变更", campaign_activation: "活动启用审批",
  complete: "完成", discover: "发现需求", research: "研究分析", prepare: "准备", generate: "生成", apply: "应用变更",
  receive: "接收任务", context: "整理上下文", decide: "解析意图", respond: "生成回复", read: "读取资料",
  probe: "测试连接", verify: "验证", execute: "执行", confirm: "确认", search: "搜索", read_pages: "读取页面",
  research_model_blocked: "研究模型调用已阻断", classify: "识别分类", qualify: "核验需求", handoff: "转交人工",
  plan_search: "制定搜索计划", execute_search: "执行搜索与取证", generate_hypotheses: "形成需求假设",
  score_and_queue: "评估并完成处理", wait_decision: "等待审批决定",
  "model.generate": "模型生成", "web.search": "网页搜索", "web.read_page": "网页读取", "email.send": "发送邮件",
  "contact.enrich": "补全联系人", "contact.verify": "验证联系人", "email.verify": "验证邮箱",
  authentication: "认证失败", permission: "权限不足", configuration: "配置不可用", quota: "达到调用额度或并发上限",
  output_limit: "模型输出达到上限，请缩小范围后重试",
  insufficient_balance: "模型账户余额不足", invalid_request: "请求参数无效", invalid_response: "返回内容无效",
  rate_limit: "请求受限", rate_limited: "请求受限", provider_error: "服务商异常", reconciliation_required: "需要人工核对",
  provider_permanent: "服务调用已阻断", provider_transient: "服务暂时不可用", provider_auth_required: "服务认证需要恢复",
  transient: "暂时错误", permanent: "永久错误", timeout: "请求超时", validation: "校验失败",
  email_raw: "原始邮件", email_draft: "邮件草稿", chat_screenshot: "聊天截图", pdf: "PDF 文档", word: "文字文档",
  excel: "电子表格", web_snapshot: "网页快照", image: "图片", audio: "音频", quote_pdf: "报价文件",
  chat_transcript: "聊天记录", email_text: "邮件文本", pdf_text: "PDF 文本", spreadsheet_text: "表格文本",
  audio_transcript: "音频转写", image_ocr: "图片识别文本", customer_statement: "客户陈述", employee_statement: "员工陈述",
  customer_reaction: "客户反馈", activity: "活动记录", employee: "员工", customer: "客户",
  customer_explicit_need: "客户明确需求", customer_quantity_and_specs: "客户提供数量与规格",
  customer_sample_or_quote_request: "客户请求样品或报价", agent_industry_inference: "智能助手行业推断",
  business: "业务邮箱", cold_outreach: "冷开发邮箱", main_business: "主业务邮箱",
  email: "邮箱", phone: "电话", role_based: "部门公共联系人", personal_business: "个人业务联系人",
  legitimate_interest: "合法利益", consent: "明确同意", existing_customer: "现有客户",
  importer: "进口商", distributor: "经销商", manufacturer: "制造商", ecommerce: "电商经营者",
  trading_company: "贸易公司", factory: "工厂", hybrid: "工贸一体", retailer: "零售商", wholesaler: "批发商",
  legal_entity: "法人企业", sole_trader: "个体经营者", natural_person: "自然人",
  quantity: "数量", unit: "单位", destination: "目的地", specification: "规格", issuer: "报价主体",
  discount: "折扣", delivery_commitment: "交期承诺", payment_terms: "付款条件", certification_commitment: "认证承诺",
  facts_missing: "缺少必要事实", quantity_invalid: "数量无效", fact_unconfirmed: "事实尚未确认",
  unit_missing: "缺少单位", unit_stale: "单位确认已失效", issuer_missing: "缺少报价主体",
  quote_inactive: "报价未生效", quote_expired: "报价已过期", approval_missing: "缺少审批", approval_invalid: "审批无效",
  approval_expired: "审批已过期", decider_invalid: "审批人无效", context_changed: "业务资料已变化",
  policy_stale: "政策已失效", basis_invalid: "报价依据无效", download_current: "下载当前版本", read_history: "查看历史版本",
  cluster_ranked: "按需求簇排序", manual_only: "仅人工准入", unavailable: "暂不可用",
  demand_signals: "需求信号记录", need_hypotheses: "需求假设记录", validated_needs: "已验证需求记录",
  opportunities: "贸易机会记录", quotations: "报价记录", handoffs: "人工接管记录", deal_outcomes: "成交结果记录",
  observed_at: "观察时间", created_at: "创建时间", closed_at: "关闭时间", requested_at: "请求时间", accepted_at: "接受时间",
  unreachable: "无法联系", no_reply: "未回复", need_not_real: "需求不真实", no_supply_found: "未找到供应",
  price_too_high: "价格过高", lost_to_competitor: "输给竞争对手", customer_went_silent: "客户失联",
  timing_mismatch: "时间不匹配", compliance_blocked: "合规阻断", margin_too_low: "利润过低", internal_no_capacity: "内部能力不足", duplicate: "重复记录",
};

/** 只转换显示文案；请求值、来源原文和业务标识保持原样。 */
export function codeLabel(value: string | null | undefined, empty = "未提供"): string {
  if (!value) return empty;
  return Object.hasOwn(labels, value) ? labels[value]! : /[\u3400-\u9fff]/.test(value) ? value : `未翻译（${value}）`;
}

export function sourcingStageLabel(value: string | null | undefined): string {
  return value === "quota" ? "额度检查" : codeLabel(value, "未知阶段");
}
