"""企业资料、持久处理、草稿与幂等请求；固定企业角色强制RLS。"""
from alembic import op

revision = "0072"
down_revision = "0071"
branch_labels = None
depends_on = None

_TABLES = ('enterprise_knowledge_documents', 'enterprise_knowledge_jobs', 'enterprise_knowledge_revisions', 'enterprise_knowledge_requests')

_RAW_MIME_BEFORE = "(kind='email_raw' AND mime_type='message/rfc822') OR (kind='chat_screenshot' AND mime_type IN ('image/png','image/jpeg','image/webp')) OR (kind='pdf' AND mime_type='application/pdf') OR (kind='word' AND mime_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document') OR (kind='excel' AND mime_type IN ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/csv')) OR (kind='web_snapshot' AND mime_type='text/html') OR (kind='image' AND mime_type IN ('image/png','image/jpeg','image/webp')) OR (kind='audio' AND mime_type IN ('audio/mpeg','audio/wav','audio/mp4'))"
_RAW_MIME_AFTER = "(kind='email_raw' AND mime_type='message/rfc822') OR (kind='chat_screenshot' AND mime_type IN ('image/png','image/jpeg','image/webp')) OR (kind='pdf' AND mime_type='application/pdf') OR (kind='word' AND mime_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document') OR (kind='excel' AND mime_type IN ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/csv')) OR (kind='web_snapshot' AND mime_type='text/html') OR (kind='image' AND mime_type IN ('image/png','image/jpeg','image/webp')) OR (kind='audio' AND mime_type IN ('audio/mpeg','audio/wav','audio/mp4')) OR (kind='text' AND mime_type IN ('text/plain','text/markdown'))"


def upgrade() -> None:
    op.drop_constraint("ck_raw_artifacts_kind_mime", "raw_artifacts", type_="check")
    op.create_check_constraint("ck_raw_artifacts_kind_mime", "raw_artifacts", _RAW_MIME_AFTER)
    op.execute("\nCREATE TABLE enterprise_knowledge_documents (\n\ttenant_id VARCHAR(40) NOT NULL, \n\tdocument_id VARCHAR(40) NOT NULL, \n\tartifact_id VARCHAR(40) NOT NULL, \n\tuploader_id VARCHAR(40) NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tcurrent_revision_id VARCHAR(40), \n\texport_state VARCHAR(16) NOT NULL, \n\tfilename VARCHAR(240) NOT NULL, \n\tpayload JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_enterprise_knowledge_documents PRIMARY KEY (tenant_id, document_id), \n\tCONSTRAINT uq_knowledge_document_artifact UNIQUE (tenant_id, artifact_id), \n\tCONSTRAINT fk_knowledge_document_artifact FOREIGN KEY(tenant_id, artifact_id) REFERENCES raw_artifacts (tenant_id, artifact_id), \n\tCONSTRAINT fk_knowledge_document_uploader FOREIGN KEY(tenant_id, uploader_id) REFERENCES employees (tenant_id, employee_id), \n\tCONSTRAINT ck_knowledge_document_status CHECK (status IN ('queued','processing','awaiting_confirmation','confirmed','failed','unknown')), \n\tCONSTRAINT ck_knowledge_document_export CHECK (export_state IN ('pending','synced','failed') AND version > 0), \n\tCONSTRAINT ck_knowledge_document_payload CHECK (jsonb_typeof(payload) = 'object')\n)\n\n")
    op.execute('CREATE INDEX ix_knowledge_document_list ON enterprise_knowledge_documents (tenant_id, created_at, document_id)')
    op.execute("\nCREATE TABLE enterprise_knowledge_jobs (\n\ttenant_id VARCHAR(40) NOT NULL, \n\tjob_id VARCHAR(40) NOT NULL, \n\tdocument_id VARCHAR(40) NOT NULL, \n\tstate VARCHAR(16) NOT NULL, \n\tlease_until TIMESTAMP WITH TIME ZONE, \n\tpayload JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_enterprise_knowledge_jobs PRIMARY KEY (tenant_id, job_id), \n\tCONSTRAINT fk_knowledge_job_document FOREIGN KEY(tenant_id, document_id) REFERENCES enterprise_knowledge_documents (tenant_id, document_id), \n\tCONSTRAINT ck_knowledge_job_state CHECK (state IN ('queued','processing','complete','failed','unknown')), \n\tCONSTRAINT ck_knowledge_job_payload CHECK (jsonb_typeof(payload) = 'object')\n)\n\n")
    op.execute('CREATE INDEX ix_knowledge_job_queue ON enterprise_knowledge_jobs (tenant_id, state, created_at, job_id)')
    op.execute("\nCREATE TABLE enterprise_knowledge_revisions (\n\ttenant_id VARCHAR(40) NOT NULL, \n\trevision_id VARCHAR(40) NOT NULL, \n\tdocument_id VARCHAR(40) NOT NULL, \n\tjob_id VARCHAR(40) NOT NULL, \n\tpayload JSONB NOT NULL, \n\tCONSTRAINT pk_enterprise_knowledge_revisions PRIMARY KEY (tenant_id, revision_id), \n\tCONSTRAINT uq_knowledge_revision_job UNIQUE (tenant_id, job_id), \n\tCONSTRAINT fk_knowledge_revision_document FOREIGN KEY(tenant_id, document_id) REFERENCES enterprise_knowledge_documents (tenant_id, document_id), \n\tCONSTRAINT fk_knowledge_revision_job FOREIGN KEY(tenant_id, job_id) REFERENCES enterprise_knowledge_jobs (tenant_id, job_id), \n\tCONSTRAINT ck_knowledge_revision_payload CHECK (jsonb_typeof(payload) = 'object')\n)\n\n")
    op.execute('\nCREATE TABLE enterprise_knowledge_requests (\n\ttenant_id VARCHAR(40) NOT NULL, \n\tactor_id VARCHAR(40) NOT NULL, \n\tkey_hash VARCHAR(64) NOT NULL, \n\trequest_hash VARCHAR(64) NOT NULL, \n\tdocument_id VARCHAR(40) NOT NULL, \n\tCONSTRAINT pk_enterprise_knowledge_requests PRIMARY KEY (tenant_id, actor_id, key_hash), \n\tCONSTRAINT fk_knowledge_request_document FOREIGN KEY(tenant_id, document_id) REFERENCES enterprise_knowledge_documents (tenant_id, document_id)\n)\n\n')
    op.execute('ALTER TABLE public.enterprise_knowledge_documents ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE public.enterprise_knowledge_documents FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tradeos_tenant_allow ON public.enterprise_knowledge_documents AS PERMISSIVE FOR ALL TO PUBLIC USING (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48)) WITH CHECK (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48))")
    op.execute("CREATE POLICY tradeos_tenant_guard ON public.enterprise_knowledge_documents AS RESTRICTIVE FOR ALL TO PUBLIC USING (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48)) WITH CHECK (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48))")
    op.execute('ALTER TABLE public.enterprise_knowledge_jobs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE public.enterprise_knowledge_jobs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tradeos_tenant_allow ON public.enterprise_knowledge_jobs AS PERMISSIVE FOR ALL TO PUBLIC USING (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48)) WITH CHECK (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48))")
    op.execute("CREATE POLICY tradeos_tenant_guard ON public.enterprise_knowledge_jobs AS RESTRICTIVE FOR ALL TO PUBLIC USING (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48)) WITH CHECK (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48))")
    op.execute('ALTER TABLE public.enterprise_knowledge_revisions ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE public.enterprise_knowledge_revisions FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tradeos_tenant_allow ON public.enterprise_knowledge_revisions AS PERMISSIVE FOR ALL TO PUBLIC USING (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48)) WITH CHECK (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48))")
    op.execute("CREATE POLICY tradeos_tenant_guard ON public.enterprise_knowledge_revisions AS RESTRICTIVE FOR ALL TO PUBLIC USING (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48)) WITH CHECK (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48))")
    op.execute('ALTER TABLE public.enterprise_knowledge_requests ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE public.enterprise_knowledge_requests FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tradeos_tenant_allow ON public.enterprise_knowledge_requests AS PERMISSIVE FOR ALL TO PUBLIC USING (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48)) WITH CHECK (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48))")
    op.execute("CREATE POLICY tradeos_tenant_guard ON public.enterprise_knowledge_requests AS RESTRICTIVE FOR ALL TO PUBLIC USING (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48)) WITH CHECK (current_user::text = 'tradeos_t_' || pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(tenant_id, 'UTF8')), 'hex'), 1, 48))")
    op.execute("DO $block$ DECLARE account record; BEGIN FOR account IN SELECT rolname FROM pg_catalog.pg_roles WHERE rolname ~ '^tradeos_t_[0-9a-f]{48}$' LOOP EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.enterprise_knowledge_documents, public.enterprise_knowledge_jobs, public.enterprise_knowledge_revisions, public.enterprise_knowledge_requests TO %I', account.rolname); END LOOP; END $block$")
    op.execute("CREATE FUNCTION knowledge_immutable_guard() RETURNS trigger LANGUAGE plpgsql AS $body$\nBEGIN\n IF TG_TABLE_NAME = 'enterprise_knowledge_documents' THEN\n  IF NEW.tenant_id <> OLD.tenant_id OR NEW.document_id <> OLD.document_id OR NEW.artifact_id <> OLD.artifact_id OR NEW.uploader_id <> OLD.uploader_id OR NEW.filename <> OLD.filename OR NEW.created_at <> OLD.created_at OR NEW.payload->'source' IS DISTINCT FROM OLD.payload->'source' THEN\n   RAISE EXCEPTION 'immutable knowledge source';\n  END IF;\n ELSE\n  IF NEW.tenant_id <> OLD.tenant_id OR NEW.revision_id <> OLD.revision_id OR NEW.document_id <> OLD.document_id OR NEW.job_id <> OLD.job_id OR (NEW.payload - 'confirmed_by' - 'confirmed_at' - 'fact_provenance') IS DISTINCT FROM (OLD.payload - 'confirmed_by' - 'confirmed_at' - 'fact_provenance') OR OLD.payload->>'confirmed_by' IS NOT NULL THEN\n   RAISE EXCEPTION 'immutable knowledge extraction';\n  END IF;\n  IF EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.payload->'fact_provenance') WITH ORDINALITY n(value,pos) FULL JOIN jsonb_array_elements(OLD.payload->'fact_provenance') WITH ORDINALITY o(value,pos) USING(pos) WHERE (n.value - 'confirmed_by' - 'confirmed_at') IS DISTINCT FROM (o.value - 'confirmed_by' - 'confirmed_at')) THEN\n   RAISE EXCEPTION 'immutable knowledge provenance';\n  END IF;\n END IF;\n RETURN NEW;\nEND $body$")
    op.execute('CREATE TRIGGER knowledge_immutable_before_update BEFORE UPDATE ON enterprise_knowledge_documents FOR EACH ROW EXECUTE FUNCTION knowledge_immutable_guard()')
    op.execute('CREATE TRIGGER knowledge_immutable_before_update BEFORE UPDATE ON enterprise_knowledge_revisions FOR EACH ROW EXECUTE FUNCTION knowledge_immutable_guard()')

def downgrade() -> None:
    op.drop_constraint("ck_raw_artifacts_kind_mime", "raw_artifacts", type_="check")
    op.create_check_constraint("ck_raw_artifacts_kind_mime", "raw_artifacts", _RAW_MIME_BEFORE)
    for name in reversed(_TABLES):
        op.drop_table(name)
    op.execute("DROP FUNCTION knowledge_immutable_guard()")
