/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/crm/analytics/loss-reasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Loss Reason Breakdown
         * @description 返回机会域已完成租户级 ABAC 的失败原因二维聚合。
         */
        get: operations["loss_reason_breakdown_crm_analytics_loss_reasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/handoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending Handoffs
         * @description 按机会域给出的最久等待优先顺序返回待接管队列。
         */
        get: operations["list_pending_handoffs_crm_handoffs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/handoffs/{handoff_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Handoff Packet
         * @description 返回机会域组装的完整接管包。
         */
        get: operations["get_handoff_packet_crm_handoffs__handoff_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/handoffs/{handoff_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Handoff
         * @description 以已断言员工身份原子接受接管；并发失败只返回固定安全冲突。
         */
        post: operations["accept_handoff_crm_handoffs__handoff_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/message-attempts/{attempt_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Manual Email
         * @description 以当前租户与员工身份发起唯一的受保护 Gmail Gateway 调用。
         */
        post: operations["send_manual_email_crm_message_attempts__attempt_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Opportunities
         * @description 以请求身份的精确机会 scope 列出机会。
         */
        get: operations["list_opportunities_crm_opportunities_get"];
        put?: never;
        /**
         * Create Opportunity
         * @description 从已验证需求创建机会；硬门槛未通过时返回无内容。
         */
        post: operations["create_opportunity_crm_opportunities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Opportunity
         * @description 读取机会公共视图（含 provenance 摘要）。
         */
        get: operations["get_opportunity_crm_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/opportunities/{opportunity_id}/mark-lost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Opportunity Lost
         * @description 以已断言员工身份确认并记录机会失败。
         */
        post: operations["mark_opportunity_lost_crm_opportunities__opportunity_id__mark_lost_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm/opportunities/{opportunity_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transition Opportunity
         * @description 请求机会域执行受状态机约束的转换。
         */
        post: operations["transition_opportunity_crm_opportunities__opportunity_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiErrorResponse
         * @description 所有 HTTP 错误共用的扁平外部契约。
         */
        ApiErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * EvidenceLevel
         * @description 证据等级。由模型判断某条证据属于哪一档——这是对事实的**分类**，
         *     不是概率估计，所以模型可以做，而且换模型后结果应保持一致。
         *
         *     顺序即强度，从弱到强。
         * @enum {string}
         */
        EvidenceLevel: "agent_industry_inference" | "public_company_event" | "employee_guess" | "customer_interest_reply" | "customer_specification" | "customer_quantity_and_timing" | "customer_sample_or_quote_request";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HandoffPacketView
         * @description 接管包视图 —— 员工看到的接管内容。
         *
         *     这个 View 的字段清单就是「不能只发一句话」的落地。员工读完
         *     应当不用再翻别的页面就能开始工作。
         *
         *     字段：
         *         handoff_id, opportunity_id, trigger
         *         account_name, country
         *         how_we_found_them
         *         why_valuable
         *         customer_verbatim:      客户原话
         *         validated_need_summary
         *         missing_information
         *         conversation_summary
         *         already_sent
         *         commitments_made
         *         suggested_next_step
         *         evidence_links
         *         requested_at, wait_seconds
         *         state, assigned_to_name
         */
        HandoffPacketView: {
            /** Account Name */
            account_name: string;
            /** Already Sent */
            already_sent?: string[];
            /** Assigned To Name */
            assigned_to_name?: string | null;
            /** Commitments Made */
            commitments_made?: string[];
            /** Conversation Summary */
            conversation_summary?: string | null;
            /** Country */
            country: string;
            /** Customer Verbatim */
            customer_verbatim: string;
            /** Evidence Links */
            evidence_links?: string[];
            /** Handoff Id */
            handoff_id: string;
            /** How We Found Them */
            how_we_found_them?: string | null;
            /** Missing Information */
            missing_information?: string[];
            /** Opportunity Id */
            opportunity_id: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** State */
            state: string;
            /** Suggested Next Step */
            suggested_next_step?: string | null;
            /** Trigger */
            trigger: string;
            /** Validated Need Summary */
            validated_need_summary?: string | null;
            /** Wait Seconds */
            wait_seconds?: number | null;
            /** Why Valuable */
            why_valuable: string;
        };
        /**
         * HandoffQueueItemView
         * @description 待接管队列的最小 packet 摘要；等待时长对 pending 行始终为整数。
         */
        HandoffQueueItemView: {
            /** Account Name */
            account_name: string;
            /** Assigned To */
            assigned_to?: string | null;
            /** Country */
            country: string;
            /** Customer Verbatim */
            customer_verbatim: string;
            /** Evidence Links */
            evidence_links?: string[];
            /** Handoff Id */
            handoff_id: string;
            /** Missing Information */
            missing_information?: string[];
            /** Opportunity Id */
            opportunity_id: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** State */
            state: string;
            /** Suggested Next Step */
            suggested_next_step?: string | null;
            /** Trigger */
            trigger: string;
            /** Wait Seconds */
            wait_seconds: number;
            /** Why Valuable */
            why_valuable: string;
        };
        /**
         * LossReason
         * @description 机会终结原因。**反馈闭环的骨架。**
         *
         *     设计稿没有这个结构（我补的）。没有它，「根据结果改进下一轮策略」
         *     只能靠感觉。现在加几乎零成本，事后补要重跑历史数据——而历史数据
         *     已经变了。
         *
         *     每个值配一句「它提示你该改什么」，因为归因的目的是改进，不是记账。
         * @enum {string}
         */
        LossReason: "unreachable" | "no_reply" | "need_not_real" | "no_supply_found" | "price_too_high" | "lost_to_competitor" | "customer_went_silent" | "timing_mismatch" | "compliance_blocked" | "margin_too_low" | "internal_no_capacity" | "duplicate";
        /**
         * ManualEmailSendBody
         * @description 员工唯一可提交的邮件内容；所有资源绑定均由服务端解析。
         */
        ManualEmailSendBody: {
            /** Body */
            body: string;
            /** Subject */
            subject: string;
        };
        /**
         * ManualEmailSendResponse
         * @description 不包含地址、正文、密钥或 URL 的安全发送结果。
         */
        ManualEmailSendResponse: {
            /** Duplicate */
            duplicate: boolean;
            /** Error Category */
            error_category: string | null;
            /** Provider Ref */
            provider_ref: string | null;
            /** Retry After Seconds */
            retry_after_seconds?: number | null;
            /** Status */
            status: string;
            /** Tool Call Id */
            tool_call_id: string | null;
        };
        /**
         * Money
         * @description 金额。不可变。
         *
         *     字段：
         *         amount:   金额，必须是 ``Decimal``
         *         currency: 币种
         *
         *     实现要求：
         *     - ``__post_init__`` 校验 ``amount`` 是 ``Decimal``，传入 ``float``
         *       直接抛错。不要"友好地"自动转换——静默转换会让错误留到生产。
         *     - 算术运算（加减）要求币种一致，不一致抛错，**不自动换算**。
         *       自动换算会隐藏"用了哪个时点的汇率"这个关键信息。
         *     - 乘除只允许乘 ``Decimal`` 或 ``int``（数量、比例），不允许
         *       两个 Money 相乘。
         *     - 舍入必须显式指定策略和精度，不依赖默认值。
         */
        Money: {
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
        };
        /**
         * OpportunityCreateRequest
         * @description 从已验证需求创建机会的入参。
         *
         *     刻意用扁平字段而不是接收 ``ValidatedNeed`` 实体：本域不 import
         *     需求域，由上层把需要的字段传进来（域间零依赖）。打分门槛输入
         *     （``category_allowed``/``minimum_order_value``/``supply_available``）
         *     也由上层按 Playbook/寻源状态填好。
         *
         *     字段：
         *         need_id, account_id, account_name, country
         *         product_category, quantity, spec_summary, application,
         *         destination, required_by, target_price
         *         current_supply_solution, current_supply_problem
         *         evidence_tier:        兼容一致性声明；只可重申 evidence.level 或
         *                               确定性推导后的 ConfidenceTier，不直接决定分数
         *         has_verified_contact
         *         category_allowed / minimum_order_value / supply_available / is_repeat_buyer_likely
         *         field_provenance:     关键字段（CRITICAL_FIELDS）的来源；present 必须各有、
         *                               且不得为 AGENT_INFERENCE（机会只存事实）
         *         estimated_order_value
         */
        OpportunityCreateRequest: {
            /** Account Id */
            account_id: string;
            /** Account Name */
            account_name: string;
            /**
             * Application
             * @default null
             */
            application: string | null;
            /** Category Allowed */
            category_allowed: boolean;
            /** Country */
            country: string;
            /**
             * Current Supply Problem
             * @default null
             */
            current_supply_problem: string | null;
            /**
             * Current Supply Solution
             * @default null
             */
            current_supply_solution: string | null;
            /**
             * Destination
             * @default null
             */
            destination: string | null;
            /** @default null */
            estimated_order_value: components["schemas"]["Money"] | null;
            /** Evidence Tier */
            evidence_tier: string;
            /** Field Provenance */
            field_provenance?: {
                [key: string]: components["schemas"]["Provenance"];
            };
            /** Has Verified Contact */
            has_verified_contact: boolean;
            /**
             * Is Repeat Buyer Likely
             * @default false
             */
            is_repeat_buyer_likely: boolean;
            minimum_order_value: components["schemas"]["Money"];
            /** Need Id */
            need_id: string;
            /** Product Category */
            product_category: string;
            /**
             * Quantity
             * @default null
             */
            quantity: number | null;
            /**
             * Required By
             * @default null
             */
            required_by: string | null;
            /**
             * Spec Summary
             * @default null
             */
            spec_summary: string | null;
            /**
             * Supply Available
             * @default null
             */
            supply_available: boolean | null;
            /** @default null */
            target_price: components["schemas"]["Money"] | null;
        };
        /**
         * OpportunityIntakeBody
         * @description 仅承载两个机会域 DTO 的 HTTP 嵌套，不复制业务字段。
         */
        OpportunityIntakeBody: {
            evidence: components["schemas"]["ValidatedNeedEvidence"];
            request: components["schemas"]["OpportunityCreateRequest"];
        };
        /**
         * OpportunityMarkLostBody
         * @description 失败原因与可选补充说明的 typed 请求体。
         */
        OpportunityMarkLostBody: {
            /** Detail */
            detail?: string | null;
            reason: components["schemas"]["LossReason"];
        };
        /**
         * OpportunityState
         * @enum {string}
         */
        OpportunityState: "qualified" | "assigned" | "contacted" | "sourcing" | "quoted" | "negotiating" | "won" | "lost";
        /**
         * OpportunityTransitionBody
         * @description 状态转换的 typed 请求体。
         */
        OpportunityTransitionBody: {
            target: components["schemas"]["OpportunityState"];
        };
        /**
         * OpportunityView
         * @description 机会视图。
         *
         *     字段：
         *         opportunity_id, account_id, account_name, country
         *         need_id, product_category
         *         state
         *         quantity, spec_summary, destination, required_by, target_price
         *         current_supply_problem:  为什么我们有机会
         *         can_source
         *         estimated_cost, estimated_profit
         *         owner, owner_name
         *         next_action, next_action_due
         *         score:          打分说明
         *         loss_reason, died_at_state
         *         created_at
         *         has_pending_handoff
         */
        OpportunityView: {
            /** Account Id */
            account_id: string;
            /** Account Name */
            account_name: string;
            /** Can Source */
            can_source?: boolean | null;
            /** Country */
            country: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Supply Problem */
            current_supply_problem?: string | null;
            /** Destination */
            destination?: string | null;
            /** Died At State */
            died_at_state?: string | null;
            estimated_cost?: components["schemas"]["Money"] | null;
            estimated_profit?: components["schemas"]["Money"] | null;
            /**
             * Has Pending Handoff
             * @default false
             */
            has_pending_handoff: boolean;
            /** Loss Reason */
            loss_reason?: string | null;
            /** Need Id */
            need_id: string;
            /** Next Action */
            next_action?: string | null;
            /** Next Action Due */
            next_action_due?: string | null;
            /** Opportunity Id */
            opportunity_id: string;
            /** Owner */
            owner?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Product Category */
            product_category: string;
            /** Provenance */
            provenance?: components["schemas"]["ProvenanceSummary"][];
            /** Quantity */
            quantity?: number | null;
            /** Required By */
            required_by?: string | null;
            score?: components["schemas"]["ScoreExplanation"] | null;
            /** Spec Summary */
            spec_summary?: string | null;
            /** State */
            state: string;
            target_price?: components["schemas"]["Money"] | null;
        };
        /**
         * Provenance
         * @description 一个字段值的来源记录。
         *
         *     字段：
         *         source_type:   来源类型
         *         source_id:     来源标识（消息 ID / 页面哈希 / 上传 ID）
         *         extracted_by:  提取者（模型版本标识或 ``"human"``）
         *         extracted_at:  提取时间
         *         confirmed_by:  确认人。``None`` 表示尚未经人工确认
         *         confirmed_at:  确认时间
         *         source_url:    来源 URL，网页类必填
         *         page_hash:     页面内容哈希，网页类必填
         *
         *     ``extracted_by`` 要记具体的模型版本标识，不要只写 ``"model"``——
         *     换模型后需要能分开评估提取质量。
         */
        Provenance: {
            /**
             * Confirmed At
             * @default null
             */
            confirmed_at: string | null;
            /**
             * Confirmed By
             * @default null
             */
            confirmed_by: string | null;
            /**
             * Extracted At
             * Format: date-time
             */
            extracted_at: string;
            /** Extracted By */
            extracted_by: string;
            /**
             * Page Hash
             * @default null
             */
            page_hash: string | null;
            /** Source Id */
            source_id: string;
            source_type: components["schemas"]["SourceType"];
            /**
             * Source Url
             * @default null
             */
            source_url: string | null;
        };
        /**
         * ProvenanceSummary
         * @description 字段来源的公共稳定摘要，不暴露内部 Enum、强类型 ID 或 ORM。
         */
        ProvenanceSummary: {
            /** Confirmed At */
            confirmed_at: string | null;
            /** Confirmed By */
            confirmed_by: string | null;
            /**
             * Extracted At
             * Format: date-time
             */
            extracted_at: string;
            /** Extracted By */
            extracted_by: string;
            /** Field Name */
            field_name: string;
            /** Page Hash */
            page_hash: string | null;
            /** Source Id */
            source_id: string;
            /** Source Type */
            source_type: string;
            /** Source Url */
            source_url: string | null;
        };
        /**
         * ScoreExplanation
         * @description 打分说明，供界面展开。
         *
         *     老板点「为什么是高意向」时看到的东西。必须能回答这个问题，
         *     否则分数不会被信任。
         *
         *     字段：
         *         sort_key:       字典序排序键（evidence_rank / value_band / supply_rank）
         *         rank_bucket:    高/中/低
         *         passed_gates
         *         failed_gates
         *         gate_reasons:   每个未通过门槛的具体原因
         *         scored_at, scorer_version
         */
        ScoreExplanation: {
            /** Failed Gates */
            failed_gates: string[];
            /** Gate Reasons */
            gate_reasons: {
                [key: string]: string;
            };
            /** Passed Gates */
            passed_gates: string[];
            /** Rank Bucket */
            rank_bucket: string;
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
            /** Scorer Version */
            scorer_version: string;
            sort_key: components["schemas"]["SortKey"];
        };
        /**
         * SortKey
         * @description 打分排序键：09 文档「字典序、证据主导」的落地。
         *
         *     evidence_rank（1–7，由 ConfidenceTier 稳定映射）、value_band（由
         *     ScoringPolicy.value_band_boundaries 划分）、supply_rank（0/1/2：
         *     False/None/True）。直接 tuple 比较，绝不加权/对数/float。
         */
        SortKey: {
            /** Evidence Rank */
            evidence_rank: number;
            /** Supply Rank */
            supply_rank: number;
            /** Value Band */
            value_band: number;
        };
        /**
         * SourceType
         * @description 来源类型。
         * @enum {string}
         */
        SourceType: "conversation" | "web_page" | "upload" | "employee_input" | "agent_inference" | "external_api";
        /**
         * ValidatedNeedEvidence
         * @description 已验证需求的证据契约（S3-6 R5/F6）。
         *
         *     从 ``NeedValidated`` / 人工录入创建机会时，必须带上这份证据——它证明
         *     这条需求**真的是客户本人表达过的**（硬边界 5 的「客户明确说过」），
         *     而不是 Agent 推断、公开企业事件或员工猜测。
         *
         *     刻意复用 ``Provenance``（含 source_type/source_id/confirmed_by/confirmed_at
         *     与其不变量），不在本 DTO 重复来源字段——两处字段会互相打架。
         *
         *     服务层强制（``service_impl.validate_validated_need_evidence``）：
         *     - ``level`` 必须 ≥ ``EvidenceLevel.CUSTOMER_INTEREST_REPLY``
         *     - ``provenance.source_type`` 仅允许 conversation/upload/employee_input
         *     - ``EMPLOYEE_INPUT`` 必须带真实人工确认对（confirmed_by/confirmed_at）
         *
         *     字段：
         *         level:      证据等级（typed，来自 shared 的 EvidenceLevel）
         *         provenance: 指向具体客户消息/上传/员工确认的 Provenance
         */
        ValidatedNeedEvidence: {
            level: components["schemas"]["EvidenceLevel"];
            provenance: components["schemas"]["Provenance"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loss_reason_breakdown_crm_analytics_loss_reasons_get: {
        parameters: {
            query?: {
                since_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: number;
                        };
                    };
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_pending_handoffs_crm_handoffs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoffQueueItemView"][];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_handoff_packet_crm_handoffs__handoff_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handoff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoffPacketView"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    accept_handoff_crm_handoffs__handoff_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handoff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 接管已被接受 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    send_manual_email_crm_message_attempts__attempt_id__send_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualEmailSendBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualEmailSendResponse"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_opportunities_crm_opportunities_get: {
        parameters: {
            query?: {
                states?: components["schemas"]["OpportunityState"][] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityView"][];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    create_opportunity_crm_opportunities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityIntakeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityView"];
                };
            };
            /** @description 未通过机会硬门槛 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_opportunity_crm_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityView"];
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    mark_opportunity_lost_crm_opportunities__opportunity_id__mark_lost_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityMarkLostBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    transition_opportunity_crm_opportunities__opportunity_id__transition_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityTransitionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 请求参数无效 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
