/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * EnterpriseOverview
         * @description 不可取得的统计保留 null，不把故障或未配置表示为零。
         */
        EnterpriseOverview: {
            /** Active Members */
            active_members?: number | null;
            /** Active Tasks */
            active_tasks?: number | null;
            /** Admins */
            admins?: number | null;
            /** Available */
            available: boolean;
            /** Customers */
            customers?: number | null;
            /** Employees */
            employees?: number | null;
            /** Enabled */
            enabled: boolean;
            /**
             * Members
             * @default []
             */
            members: components["schemas"]["PlatformMember"][];
            /** Name */
            name: string;
            /** Opportunities */
            opportunities?: number | null;
            /** Tenant Id */
            tenant_id: string;
            /** Validated Needs */
            validated_needs?: number | null;
        };
        /**
         * PlatformMember
         * @description 概览允许公开的成员姓名及企业身份，不含登录或私人资料。
         */
        PlatformMember: {
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "employee";
        };
        /**
         * PlatformOverview
         * @description 各企业独立只读快照；generated_at 为概览组装时间。
         */
        PlatformOverview: {
            /** Enterprises */
            enterprises: components["schemas"]["EnterpriseOverview"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * PlatformSessionResponse
         * @description 平台会话无企业员工 DTO，不可作为企业工作台身份使用。
         */
        PlatformSessionResponse: {
            /** Csrf Token */
            csrf_token: string;
            /** Display Name */
            display_name: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Role
             * @default platform_admin
             * @constant
             */
            role: "platform_admin";
            /** Username */
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Password
                     * Format: password
                     */
                    password: string;
                    /** Username */
                    username: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformSessionResponse"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    current_session_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformSessionResponse"];
                };
            };
        };
    };
    overview_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformOverview"];
                };
            };
        };
    };
}
